### ISSUE TITLE
Archief – Extern – Uitslagen.  Problemen met weergave seizoenen

### ISSUE THREAD

**Issue by haverver** [hoogland/SVN#53]
Seizoenen vóór 2005-2006 zijn niet in het pop-up scherm zichtbaar. (zie issue 34)

Na Archief – Extern – Uitslagen verschijnen alle wedstrijduitslagen van Krimpen 1. Dit is na uitvoering van de volgende regel niet meer in dezelfde sessie terug te halen.

Na keuze seizoen en team blijft de URL ongewijzigd met seizoen=0@team =1. Als ik de URL wijzig zijn alle seizoenen en teams oproepbaar.

**Comment by hoogland** [comment]
Zelfde als item #34 seizoenen werden niet weergegeven als er geen interne competitie aanwezig was. Is nu aangepast naar ook externe competitie.

De url blijft nu altijd hetzelfde door het gebruik maken van AngularJS. Gaat nog wel netter worden en de standaard competitie kan worden aangepast in class.settings.php (in de map includes)
